- hosts: localhost
  vars:
    - user_name: podlove
    - database_name: "{{ user_name }}"
    - home_dir: "/home/{{ user_name }}"
    - default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  tasks:
    - name: "Include secret vars"
      include_vars: secrets.yml

    - name: Add sury.org signing key - do not download if present
      apt_key:
        id: 15058500A0235D97F5D10063B188E2B695BD4743
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add sury.org repository for php 8.1
      apt_repository:
        repo: deb https://packages.sury.org/php/ bullseye main
        state: present

    - name: Install required php packages
      apt:
        name: ["php8.1", "php8.1-mysql"]

    - name: Add the unix user with a bash shell
      user:
        name: "{{ user_name }}"
        shell: /bin/bash

    - name: Download wordpress source
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "{{ home_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create a new mysql database
      community.mysql.mysql_db:
        name: "{{ database_name }}"
        login_password: "{{ mariadb_root_password }}"
        state: present
